sudo: required

services:
  - docker

before_install:
  - docker build -t dockerlearn -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerlearn npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "dockerLearn"
  env: "Dockerlearn-env"
  bucket_name: "elasticbeanstalk-us-east-1-618590180755"
  bucket_path: "Dockerlearn"
  on:
    branch: main